server:
  port: 51801
spring:
  application:
    name: leadnews-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${TENCENT_VPS}:3306/leadnews_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: oreki
    password: ${PASSWORD}
  cloud:
    nacos:
      discovery:
        server-addr: ${TENCENT_VPS}:8848
      config:
        server-addr: ${TENCENT_VPS}:8848
        file-extension: yml
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.user.entity